### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by redox** [julien-maurel/jQuery-Storage-API#17]
Hey @julien-maurel ,

do you mind adding a LICENSE file? I would love to use your project :)

**Comment by redox** [comment]
Oh, it's inline in the header of the project: MIT :)

**Comment by julien-maurel** [comment]
Hi, You're right, it's in the main file but licence file is missing, i'll add it in a next version

**Comment by redox** [comment]
Awesome, thank you @julien-maurel !
