### ISSUE TITLE
Problem with "js error: TypeError: s is undefined"

### ISSUE THREAD

**Issue by wawanawna** [julien-maurel/jQuery-Storage-API#23]
Hello, thx a lot for nice js lib, found one error, maybe following may help to fix it.

I am debugging that js error.

stack:
_get()
storage._callMethod(f=_get(storage), a=["selectedConnectedLogseneAppForSystem"])
storage.get()
selectDefaultLogseneSystem()
(anonymous)()
j

Here is the piece of code in storageapi which fails:
     }else if(l==2){
      // If only 2 arguments, return value directly
      try{
        return JSON.parse(s.getItem(a1));
      }catch(e){
        return s.getItem(a1);
      }
    }else{

that return s.getItem...

where:
s=window[storage]

and storage="localCookieStorage"

We saw this error from time to time. Is it possible to add check if 'localCookieStorage' exists or?

Thx.

**Comment by julien-maurel** [comment]
Hi,
It's strange. localCookieStorage and sessionCookieStorage are initialized at line 412 & 413.
At my point of view, the only way to have this error is to not include jQuery cookie plugin before my plugin (in this case, these lines are not executed).
Cookie plugin is included before this plugin?

**Comment by wawanawna** [comment]
Hi again, thx for quick response.


We don't use jQuery cookie plugin because we use relatively new FF & Safary.


Will add plugin and we will see if it helps soon, thx a lot.

**Comment by julien-maurel** [comment]
localCookieStorage/sessionCookieStorage are fallbacks when native localStorage/sessionStorage are not supported.
So if you have this error with "localCookieStorage" in "storage" variable, that mean call to _testStorage function at line 296 return false, that is not normal if your browser support native storage.
Can you check that?

**Comment by wawanawna** [comment]
Now we are using .min version in our production. If cookie js will not help we will switch to full version and will debug. Hope your assumption was right and we have a fix:)

**Comment by julien-maurel** [comment]
I think it will help you, but if your browser support native storage, you should not need cookie plugin.
Cookie plugin is needed only on old browsers to have fallback.

**Comment by wawanawna** [comment]
My colleague told me that your fix helped. Thx a lot. Maybe his FF version (39.0.3) has issue.
