### ISSUE TITLE
doesn't work with arrays after 1 layer

### ISSUE THREAD

**Issue by mctrivia** [julien-maurel/jQuery-Storage-API#28]
the following works.  output is [6,6,8]

			$.localStorage.set('abc',[5,6,8]);
			$.localStorage.set('abc.0',6);
			console.log($.localStorage.get('abc'));

this does not.  output is Object {0: 6}

			$.localStorage.set('abc.78',[5,6,8]);
			$.localStorage.set('abc.78.0',6);
			console.log($.localStorage.get('abc.78'));

**Comment by mctrivia** [comment]
since I can't decifer code well enough to fix I wrote this as a work around.  hope it helps you fix


var dataSet=function(item,value) {
		//get base value to make sure arrays don't get screwed updateCommands
		var itemParts=item.split('.');
		var data=$.localStorage.get(itemParts[0]);
		if (data===null) data={};	//make sure there is an object
		
		//move pointer to requested piece of data
		var pointer=data;
		var count=itemParts.length-1;
		for (let i=1;i<count;i++) {
			if (typeof pointer[itemParts[i]]==="undefined") pointer[itemParts[i]]={};	//create an object if doesn't exist
			pointer=pointer[itemParts[i]];
		}
		
		//modify entry
		pointer[itemParts[count]]=value;
		
		//save changes	
		$.localStorage.set(itemParts[0],data);	
}


now the following gets what I would expect.


			dataSet('abc.78',[5,6,8]);
			dataSet('abc.78.0',6);
			console.log($.localStorage.get('abc.78'));

**Comment by julien-maurel** [comment]
Hi,
I pushed a new version to fix that.
Thanks
