### ISSUE TITLE
Remove jQuery dependency requirement?

### ISSUE THREAD

**Issue by futpib** [julien-maurel/jQuery-Storage-API#29]
This library has barely anything to do with jQuery and uses it for some utilities like `isArray`, `isPlainObject` and as a namespace where the API is exposed.

Just like [carhartl/jquery-cookie](https://github.com/carhartl/jquery-cookie) turned into [js-cookie/js-cookie](https://github.com/js-cookie/js-cookie). this project can be turned into js-cookie-api without loosing any features or value, but getting rid of a significant unnecessary dependency.

Related jquery-cookie issue: [carhartl/jquery-cookie/#349](https://github.com/carhartl/jquery-cookie/issues/349)

**Comment by julien-maurel** [comment]
i already had this reflection a few days ago when i did last fix., but for the moment i didn't take time to do it. i'll did it one day but not now. i think before end of year

**Comment by julien-maurel** [comment]
I release a new plugin.
https://github.com/julien-maurel/js-storage

Thanks
