### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setItem' of undefined

### ISSUE THREAD

**Issue by Dutsik** [julien-maurel/jQuery-Storage-API#31]
when including a page into Facebook as an iframe the plugin throws an exception:

You can check it here:
1. https://www.facebook.com/myxtramile/?sk=app_822422207880350
2. press Postuler

and the orginal which is working just fine:
1. https://adutskevich.com/landings/myxtramile/
2. press Postuler 

Looks like there is a problem with nesting frame

**Comment by julien-maurel** [comment]
what browser do you use?
i try your link on ff and chrome, i have no issue.
and i ran tests (Jasmine/SpecRunner.html) by including this page in an iframe and no issue too

**Comment by Dutsik** [comment]
You are absolutelly right it looks like all is fine in FF. The issue is in chrome, Version 53.0.2785.116 m. See the screenshot below.

![image](https://cloud.githubusercontent.com/assets/584244/18911566/71da41a6-8586-11e6-9627-3a53b83b9af6.png)

**Comment by julien-maurel** [comment]
Exactly same version of chrome and no issue/log when I click...

**Comment by Dutsik** [comment]
Ok, I found the issue.

I set to block 3rd party cookies in chrome, so it is likely that your plugin fails when there is no possibility to create a cookie storage or smth. Anyway, thanks for your time. Now i know that all is almost working ;)
Screenshot is attached.
![image](https://cloud.githubusercontent.com/assets/584244/18912863/61929dc8-858d-11e6-93bf-7bf0d6e6917e.png)

**Comment by julien-maurel** [comment]
yw
